application: personal_web
version: 1
api_version: 1
runtime: python27
threadsafe: yes

handlers:
- url: /.*
  script: main.app




libraries:
- name: flask
  version: 0.21

- name: Jinja2
  version: latest    

