application: personalweb
version: 1
api_version: 1
runtime: python27
threadsafe: yes

handlers:
- url: /.*
  script: main.app


libraries:
- name: flask
  version: latest


- name: jinja2
  version: latest    

- name: ssl
  version: latest

builtins:
- appstats: on

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^env$
- ^\.git$
- ^\.ropeproject$
